apiVersion: v1
kind: Secret
metadata:
  name: lb-service-account-token
  namespace: {{ .Values.namespace | default "keda" }}
  annotations:
    kubernetes.io/service-account.name: lb-service-account
type: kubernetes.io/service-account-token

