apiVersion: v1
kind: Service
metadata:
  name: pdflb
  namespace: {{ .Values.namespace | default "keda" }}
  annotations:
    networking.gke.io/load-balancer-type: Internal
spec:
  selector:
    app: loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.loadbalancer.containerPort }}
  type: LoadBalancer

