apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertexai-summary-deployment
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vertexai-summary
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: vertexai-summary
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: vertexai-summary
        image: gcr.io/{{ .Values.pullImagefrom }}/disearch/vertexai-summary:1.0.8
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.vertexaiSummary.containerPort }}

