apiVersion: v1
kind: ConfigMap
metadata:
  name: disearch-configmap
  namespace: default
data:
  ALLOWED_ORIGIN: {{ .Values.disearch.allowedOrigin }} 
  AUTH_EMAIL: {{ .Values.disearch.authEmail }}
  schema: {{ .Values.disearch.schema }}
  appName: {{ .Values.disearch.appName}}
  IS_PENSDOWN: {{ .Values.disearch.IS_PENSDOWN}}
  IS_CONTEXT: {{ .Values.disearch.IS_CONTEXT}}
  DB_USER: {{ .Values.disearch.dbUser }}
  GCP_BUCKET: {{ .Values.disearch.gcpBucket }} 
  DB_HOST: {{ .Values.disearch.dbHost }}
  DB_PASSWORD: {{ .Values.disearch.dbPassword }}
  DOCUMENT_CHAT_URL: {{ .Values.disearch.DOCUMENT_CHAT_URL }}
  LOG_INDEX: {{ .Values.disearch.projectID }} 
  project_id: {{ .Values.disearch.projectID }}
  vertex_ai_search_summary_url: {{ .Values.disearch.vertex_ai_search_summary_url }}
  vertex_ai_followup_url: {{ .Values.disearch.vertex_ai_followup_url }}
  IS_VERTEX_AI: {{ .Values.disearch.IS_VERTEX_AI }}
  vertex_ai_search_base_url: {{ .Values.disearch.vertex_ai_search_base_url }}
  vertex_ai_init_base_url: {{ .Values.disearch.vertex_ai_init_base_url }}
  APP_VERSION: {{ .Values.disearch.APP_VERSION }}
