apiVersion: apps/v1
kind: Deployment
metadata:
  name: disearch-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: disearch
  template:
    metadata:
      labels:
        app: disearch
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: disearch
        image: gcr.io/{{ .Values.projectID }}/disearch/disearch:1.0.8
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.disearch.containerPort }}
        envFrom:
        - configMapRef:
            name: disearch-configmap  # Referencing the ConfigMap here
